package com.example.demo.ui.resources

object AppText {
    object Common {
        const val Back = "‹"
        const val Next = "›"
        const val Save = "保存"
        const val Complete = "完成"
        const val Cancel = "取消"
        const val Confirm = "确认"
        const val NotSet = "未设置"
        const val China = "中国"
        const val Female = "女"
        const val Male = "男"
    }

    object Navigation {
        const val Fitness = "体能"
        const val Records = "记录"
        const val Explore = "探索"
        const val Me = "我"

        fun unavailable(name: String) = "$name 功能将在后续版本开放"
    }

    object Health {
        const val Today = "今天"
        const val EditCards = "编辑卡片"
        const val DataUnavailable = "健康数据暂时不可用"
        const val Calendar = "日历"
        const val SportDevice = "运动设备"
        const val StepsUnit = "步"
        const val CaloriesUnit = "Kcal"
        const val MinutesUnit = "Min"
        const val ManageOrder = "管理卡片顺序（最少展示3项）"
        const val MinimumCards = "最少展示三项日常数据"
        const val MoreDailyData = "更多日常数据"
        const val RestoreDefaults = "恢复默认数据"
        const val Add = "添加"
        const val Remove = "删除"
        const val DragHandle = "⠿"

        const val WeeklyPlan = "本周计划"
        const val TodayActivity = "今日活动"
        const val TrainingLoad = "本周负荷"
        const val TrainingAssessment = "训练量评估"
        const val Recovery = "体力恢复"
        const val RunningAbility = "跑步能力"
        const val CyclingAbility = "骑行FTP"
        const val HeartRate = "心率"
        const val Stress = "压力"
        const val Sleep = "睡眠"
        const val HrvAssessment = "HRV评估"
        const val RestingHeartRate = "静息心率"
        const val HealthCheck = "健康快测"
        const val BodyManagement = "体型管理"

        fun pendingFeature(title: String) = "${title}功能后续实现"
    }

    object Auth {
        const val Register = "注册"
        const val Login = "登录"
        const val AccountLogin = "账号登录"
        const val AccountPlaceholder = "输入手机号或邮箱"
        const val Password = "密码"
        const val ForgotPassword = "忘记密码?"
        const val Version = "V4.8.1.14"
        const val PhoneRegister = "手机号注册"
        const val EmailRegister = "邮箱注册"
        const val EmailPlaceholder = "请输入邮箱"
        const val SendCode = "发送验证码"
        const val VerificationCode = "输入验证码"
        const val Resend = "重新发送"
        const val GetCode = "获取验证码"
        const val CodeHelp = "收不到验证码?"
        const val FindPassword = "找回密码"
        const val NextStep = "下一步"
        const val SetLoginPassword = "设置登录密码"
        const val SetNewPassword = "设置新密码"
        const val NewPasswordPlaceholder = "输入新的密码"
        const val ConfirmPasswordPlaceholder = "再次输入密码"
        const val ConfirmNewPasswordPlaceholder = "再次输入新密码"
        const val PasswordRule = "6-20位必须包含字母和数字"
        const val Account = "账号"
        const val PrivacyPolicy = "隐私政策"
        const val ServiceTerms = "服务条款"
        const val ReadTerms = "阅读并同意以下条款，"
        const val AgreeAndContinue = "同意并继续"
        const val Unavailable = "抱歉，该功能还在实现中"
        const val GotIt = "知道了"
        const val ThirdPartyAccount = "第三方账号"
        const val Feedback = "◔ 建议&反馈"
        const val ClearInput = "清空输入"
        const val HidePassword = "隐藏密码"
        const val ShowPassword = "显示密码"
        const val PhonePlaceholder = "输入手机号"
        const val ChinaDialingCode = "+86"
        const val Logo = "COROS Logo"
    }

    object Profile {
        const val CompletionTitle = "完善个人信息"
        const val CompletionDescription = "以下信息可以帮助我们对体育科学做出更准确的预测，请仔细填写。"
        const val PersonalInfo = "个人信息"
        const val Username = "用户名"
        const val UsernamePlaceholder = "输入用户名"
        const val BirthDate = "出生日期"
        const val Height = "身高"
        const val Weight = "体重"
        const val Measurement = "公英制"
        const val Phone = "手机"
        const val PhonePlaceholder = "输入手机号"
        const val CountryRegion = "国家与地区"
        const val FillIn = "去填写"
        const val Gender = "性别"
        const val AddAvatar = "添加头像"
        const val EditUsername = "修改用户名"
        const val Close = "关闭"
        const val TakePhoto = "拍照片"
        const val Album = "相册"
        const val HeightPicker = "身高 (cm)"
        const val WeightPicker = "体重 (kg)"
    }

    object Account {
        const val My = "我的"
        const val Complete = "资料已完善"
        const val Incomplete = "资料待完善"
        const val PersonalInfo = "个人信息"
        const val AccountSection = "账户"
        const val LoginAccount = "登录账号"
        const val Logout = "退出登录"
        const val DeleteAccount = "注销账户"
        const val DeleteConfirmation = "是否确认注销账号"
        const val DefaultUser = "用户"
    }
}
